language: R
cache: packages

pandoc_version: 2.3.1

script: Rscript -e 'rmarkdown::render(input = "index.Rmd")'

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'

deploy:
  provider: script
  script: Rscript deploy.R
  skip_cleanup: true
